import { describe, expect, it } from 'vitest';
import {
  createEmptyOverrideForm,
  normalizeTimeSlotsInput,
  validateConfigForms,
  validateOverrideForm,
} from './entranceBookingHelpers';

describe('entranceBookingHelpers', () => {
  it('normalizes valid time slots and rejects invalid ones', () => {
    expect(normalizeTimeSlotsInput('09:00, 12:00, 15:00')).toEqual(['09:00', '12:00', '15:00']);
    expect(() => normalizeTimeSlotsInput('9am')).toThrow('Invalid time slot');
  });

  it('validates config forms into numeric payloads', () => {
    expect(
      validateConfigForms(
        {
          is_active: true,
          price: '75000',
          available_from: '2026-03-01',
          available_until: '2026-03-31',
          time_slots: '09:00, 12:00',
        },
        {
          max_tickets_per_booking: '5',
          booking_window_days: '30',
          auto_generate_days_ahead: '60',
          default_slot_capacity: '100',
        }
      )
    ).toEqual({
      normalizedTimeSlots: ['09:00', '12:00'],
      price: 75000,
      maxTicketsPerBooking: 5,
      bookingWindowDays: 30,
      autoGenerateDaysAhead: 60,
      defaultSlotCapacity: 100,
    });
  });

  it('validates override forms and keeps whole-date overrides slotless', () => {
    const form = createEmptyOverrideForm();
    form.date = '2026-03-30';
    form.is_closed = false;
    form.capacity_override = '40';
    form.reason = 'Private event';

    expect(validateOverrideForm(form)).toEqual({
      date: '2026-03-30',
      time_slot: null,
      is_closed: false,
      capacity_override: 40,
      reason: 'Private event',
    });
  });
});
