import { useCallback, useEffect, useState } from 'react';
import { supabase } from '../../../lib/supabase';
import type { EntranceTicket } from '../../../hooks/useEntranceTicket';
import type { TicketBookingSettings } from '../../../hooks/useTicketBookingSettings';
import { createSettingsFormState, createTicketFormState, validateConfigForms } from './entranceBookingHelpers';
import type { SettingsFormState, TicketFormState } from './entranceBookingTypes';

type UseEntranceBookingConfigFormArgs = {
  ticket: EntranceTicket | null | undefined;
  bookingSettings: TicketBookingSettings | null | undefined;
  refetchTicket: () => Promise<unknown>;
  refetchSettings: () => Promise<unknown>;
  showToast: (type: 'success' | 'error', message: string) => void;
};

export function useEntranceBookingConfigForm({
  ticket,
  bookingSettings,
  refetchTicket,
  refetchSettings,
  showToast,
}: UseEntranceBookingConfigFormArgs) {
  const [ticketForm, setTicketForm] = useState<TicketFormState | null>(null);
  const [settingsForm, setSettingsForm] = useState<SettingsFormState | null>(null);
  const [savingConfig, setSavingConfig] = useState(false);

  useEffect(() => {
    if (!ticket) return;
    setTicketForm(createTicketFormState(ticket));
  }, [ticket]);

  useEffect(() => {
    if (!bookingSettings) return;
    setSettingsForm(createSettingsFormState(bookingSettings));
  }, [bookingSettings]);

  const handleSaveConfig = useCallback(async () => {
    if (!ticket || !ticketForm || !settingsForm) return;

    try {
      const validated = validateConfigForms(ticketForm, settingsForm);
      setSavingConfig(true);

      const { error: ticketUpdateError } = await supabase
        .from('tickets')
        .update({
          is_active: ticketForm.is_active,
          price: validated.price,
          available_from: `${ticketForm.available_from} 00:00:00`,
          available_until: `${ticketForm.available_until} 00:00:00`,
          time_slots: validated.normalizedTimeSlots,
          updated_at: new Date().toISOString(),
        })
        .eq('id', ticket.id);

      if (ticketUpdateError) throw ticketUpdateError;

      const { error: settingsUpsertError } = await supabase
        .from('ticket_booking_settings')
        .upsert({
          ticket_id: ticket.id,
          max_tickets_per_booking: validated.maxTicketsPerBooking,
          booking_window_days: validated.bookingWindowDays,
          auto_generate_days_ahead: validated.autoGenerateDaysAhead,
          default_slot_capacity: validated.defaultSlotCapacity,
        });

      if (settingsUpsertError) throw settingsUpsertError;

      await Promise.all([refetchTicket(), refetchSettings()]);
      showToast('success', 'Entrance booking settings saved');
    } catch (error) {
      showToast('error', error instanceof Error ? error.message : 'Failed to save entrance booking settings');
    } finally {
      setSavingConfig(false);
    }
  }, [refetchSettings, refetchTicket, settingsForm, showToast, ticket, ticketForm]);

  return {
    ticketForm,
    setTicketForm,
    settingsForm,
    setSettingsForm,
    savingConfig,
    handleSaveConfig,
  };
}
